FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN apk add --no-cache python3 make g++ \
    && npm install \
    && apk del python3 make g++

COPY . .

# ✅ Add this line
COPY .env .env

EXPOSE 5000

CMD ["npm", "start"]
