apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: frontendminikubes:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000 # Change this if your app uses a different port
